FROM ubuntu:16.04
MAINTAINER codolutions

RUN apt-get update && apt-get install -y python-software-properties software-properties-common
RUN add-apt-repository ppa:webupd8team/java
RUN echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 boolean true" | debconf-set-selections
RUN apt-get update
RUN apt-get install -y oracle-java8-installer maven
RUN apt-get install -y git

